### ISSUE TITLE
Command Bar

### ISSUE THREAD

**Issue by voylin** [VoylinsGamedevJourney/GoZen#11]
### Discussed in https://github.com/voylin/GoZen/discussions/8

**How would a command paletta improve use-ability:**
- Time-saving: Quick way of doing actions;
- Convenient: If you can't find how to do something, you can search for it;
- Customize-ability: People can create their own commands to do certain things quicker;

**How to implement:**
Should be some kind of bar overlay in which can be typed. When hovering over commands a description should popup somewhere (not certain about how this would work yet).

-------------------------------------------------------------------------
<div type='discussions-op-text'>
<sup>Originally posted by **Wilker-uwu** June 20, 2023</sup>

in practice, an implementation would look like this:

- reserve a simple, easily reachable keybind (e.g `:`);
- such a keybind should open a single-line text box with a reserved character in the beginning -- when in doubt, choose a colon `:` like in most editors and CLIs, a greater-than `>` symbol like in VSCode, or just a slash `/` symbol like a lot of people who are familiar with Minecraft commands.
- deleting such a symbol should either cancel the prompt, or provide a project-wide file browsing list with all possible files;
- all searches should be done with a fuzzy search function, ranking results by closest first match, but not necessarily discarding any options not matching it;
- you might need to look for a solution for disambiguation early on. there's a chance that a plugin might look to replace a function or give the same name with a different meaning. i don't know any standards about this;
- subcommands are also a thing, both for keybinds and commands. the docs for the Helix editor has a more intuitive way of handling it in text, i think;
- bonus points if you decide to make full descriptions on top of keybind suggestions;

additionally, i think this should also make it possible to apply the same static function solution when implementing keybinds to the program. if you need a sequence of keys, set up a "leading key", or multiple ones depending on the configuration and then its subcommands. for instance, `Ctrl+q` and then `!` would quit the program quit without saving as if typing in `:quit!` or `:q!` to quit as well (exclamation mark means ignore failsafes, like checking if the project had any unsaved changes), but `Ctrl+q` and `s` would `:write-quit` or `:wq`, and `Ctrl+q` and then **`S`** (notice the uppercase letter) would be the equivalent of "Save" and "Save As...".

i think this should make the project much easier going forward.</div>

-------------------------------------------------------------------------

This could go together with a possible 'Zen mode' in which all possibly not needed buttons are completely hidden and the main way of controlling things in the editor is by keyboard using the command palette.

Edit:
This got added to the Github project for GoZen. The command bar still needs some polishing and fixing:

- [x] Use arrow keys to select command;
- [x] Make UI more readable;

**Comment by CollCaz** [comment]
I have been using the [GDShell](https://github.com/Kubulambula/Godot-GDShell) plugin in my own project and i really like it.
If you think this would be a good fit for GoZen then i could implement it with custom UI and all that.
If you want a custom solution instead then i might be able to come up with something based on GDshell but wont have as many features

**Comment by aappaapp** [comment]
imo GDShell is a bit too complicated for a simple command palette.

**Comment by voylin** [comment]
Been working today on finalizing some of the basic functionalities for a first version of the command bar, most of it was already made so it is just slightly cleaning up, adding the functionality of clicking to select the command and using the arrow keys to select the command.
Probably needs a little more work tomorrow before I push the changes. 

The original issue had much more functionality described, but this will be for after version 1 is released as this is just a small quality of life feature and the focus for now should be on the actual video editing parts. So after the push I'll be closing this issue and keep the suggestions of further improvements to the comment bar as notes for the time being.

**Comment by voylin** [comment]
using arrow keys to select the command and clicking commands now work. There is still a problem with the already set commands, but this will change in the future anyway. The last changes were done with commit: daf37ce3

Closing this issue for now and will stop working further on this until alpha/beta testing starts.

**Comment by voylin** [comment]
Completely broken ... again, fixing this one later. 

When selecting a command, the editor crashes

**Comment by voylin** [comment]
Closing this issue for now, this isn't going to happen until after the first release to limit the amount of moving parts which can cause trouble.
