### ISSUE TITLE
File dialog

### ISSUE THREAD

**Issue by voylin** [VoylinsGamedevJourney/GoZen#2]
The 'File Explorer' module uses the default Godot file explorer. This should be changed to a custom file explorer with the option for saving certain folders (bookmarks).

**Things to note:**
- We should have the default folders of each operating system easily accesible;
- Bookmarks are a must;
- Bookmarks need to become part of the FileExplorerInterface for other module creators to use;
- Must use the default theme; (Default theme at this point is still a work in progress)
- Must only have the necessary stuff.

We need to keep the base version of GoZen light, minimalistic looking and simple to use. So whoever wants to have a go at making this file explorer, please take this in mind. It can look and feel like any other file explorer.

Edit:
I've added this to the project page for GoZen.
The TO-DO's for this to be finished are:

- [ ] UI;
- [ ] Zen-mode UI;
- [ ] Save previous location which was accessed;
- [ ] Be able to create folders;
- [ ] Be functional as a file explorer basically;

The reason why I am implementing my own solution is as a learning experience and it gives people who want to make their own file explorer module easier. Feel free to create a module which uses the systems file explorer, or even the Godot file explorer. I have some plans on making it worth it to have our own made File Explorer, but those benefits will show later.

My intention is to make it when you open the file explorer when intending to add files to your project, that you have a split view of your system files and your project files. In the project files will also be the folder for adding global accessible files (Files which you can access from all your projects).

**Comment by CollCaz** [comment]
What do you think about using [This](https://github.com/98teg/NativeDialogs) plugin?
It adds a a native file dialog that uses the OS's own default file explorer but also adds other things that might be useful in the future such as OS notifications

And it works on Linux MacOS and windows

Users can take care of their own bookmarks on their machines.
Even if this solution is not acceptable, The other features of this plugin would still be useful at some point.

**Comment by ZachAR3** [comment]
> What do you think about using [This](https://github.com/98teg/NativeDialogs) plugin? It adds a a native file dialog that uses the OS's own default file explorer but also adds other things that might be useful in the future such as OS notifications
> 
> Edit: [Here](https://github.com/98teg/NativeDialogs/blob/master/doc/native_file_dialog.md) is the documentation for the Native file dialog
> 
> And it works on Linux MacOS and windows
> 
> Users can take care of their own bookmarks on their machines. Even if this solution is not acceptable, The other features of this plugin would still be useful at some point.

That's really interesting! If that doesn't work native file dialogs sharp has worked well for me if you end up using C# in your project https://github.com/milleniumbug/NativeFileDialogSharp

**Comment by voylin** [comment]
> What do you think about using [This](https://github.com/98teg/NativeDialogs) plugin? It adds a a native file dialog that uses the OS's own default file explorer but also adds other things that might be useful in the future such as OS notifications
> 
> Edit: [Here](https://github.com/98teg/NativeDialogs/blob/master/doc/native_file_dialog.md) is the documentation for the Native file dialog
> 
> And it works on Linux MacOS and windows
> 
> Users can take care of their own bookmarks on their machines. Even if this solution is not acceptable, The other features of this plugin would still be useful at some point.

Thanks for the suggestion! Was busy with other parts of the editor but I think I'll try out this plugin in the project, if it works well it'll stay, else I'll create a separate module which uses this plugin instead.

**Comment by voylin** [comment]
"File dialog" got solved by using native_dialog. Will close this as this is solved for now.
