### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by RumarioVR** [VoylinsGamedevJourney/gozen#95]
### Problem or limitation

Android/VR-Mobile support? 

### Feature / enhancement to solve the problem

Android/VR-Mobile support?

**Comment by voylin** [comment]
Adding Android is on the future to-do list. However, at this moment I'm mainly a one man team and I need to get GoZen usable first on Linux before I start supporting other platforms. There has been some requests for an Android port, would probably not be for the GoZen project, but a separate project as the mobile version will never be able to support all the modular stuff. Probably more something for GoZen Lite.

If you are just talking about Android support for the GDExtension which gives the video playback, this will be handled as part of this, but again, it will take time.

**Comment by voylin** [comment]
No comment received for some months so closing this one.
